[package]
name = "schnorr-signature"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
hex = "0.4.3"
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
